// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// vec_dist
double vec_dist(NumericVector x, NumericVector y);
RcppExport SEXP _ldmppr_vec_dist(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(vec_dist(x, y));
    return rcpp_result_gen;
END_RCPP
}
// full_product
double full_product(double xgrid, double ygrid, double tgrid, NumericMatrix data, NumericVector params);
RcppExport SEXP _ldmppr_full_product(SEXP xgridSEXP, SEXP ygridSEXP, SEXP tgridSEXP, SEXP dataSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type xgrid(xgridSEXP);
    Rcpp::traits::input_parameter< double >::type ygrid(ygridSEXP);
    Rcpp::traits::input_parameter< double >::type tgrid(tgridSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(full_product(xgrid, ygrid, tgrid, data, params));
    return rcpp_result_gen;
END_RCPP
}
// C_theta2_i
double C_theta2_i(NumericVector xgrid, NumericVector ygrid, double tgrid, NumericMatrix data, NumericVector params, NumericVector bounds);
RcppExport SEXP _ldmppr_C_theta2_i(SEXP xgridSEXP, SEXP ygridSEXP, SEXP tgridSEXP, SEXP dataSEXP, SEXP paramsSEXP, SEXP boundsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type xgrid(xgridSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ygrid(ygridSEXP);
    Rcpp::traits::input_parameter< double >::type tgrid(tgridSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bounds(boundsSEXP);
    rcpp_result_gen = Rcpp::wrap(C_theta2_i(xgrid, ygrid, tgrid, data, params, bounds));
    return rcpp_result_gen;
END_RCPP
}
// conditional_sum
double conditional_sum(NumericVector obs_t, double eval_t, NumericVector y);
RcppExport SEXP _ldmppr_conditional_sum(SEXP obs_tSEXP, SEXP eval_tSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type obs_t(obs_tSEXP);
    Rcpp::traits::input_parameter< double >::type eval_t(eval_tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(conditional_sum(obs_t, eval_t, y));
    return rcpp_result_gen;
END_RCPP
}
// conditional_sum_logical
double conditional_sum_logical(NumericVector obs_t, double eval_t, LogicalVector y);
RcppExport SEXP _ldmppr_conditional_sum_logical(SEXP obs_tSEXP, SEXP eval_tSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type obs_t(obs_tSEXP);
    Rcpp::traits::input_parameter< double >::type eval_t(eval_tSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(conditional_sum_logical(obs_t, eval_t, y));
    return rcpp_result_gen;
END_RCPP
}
// vec_to_mat_dist
NumericVector vec_to_mat_dist(NumericVector eval_u, NumericMatrix obs_u);
RcppExport SEXP _ldmppr_vec_to_mat_dist(SEXP eval_uSEXP, SEXP obs_uSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type eval_u(eval_uSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type obs_u(obs_uSEXP);
    rcpp_result_gen = Rcpp::wrap(vec_to_mat_dist(eval_u, obs_u));
    return rcpp_result_gen;
END_RCPP
}
// dist_one_dim
NumericVector dist_one_dim(double eval_t, NumericVector obs_t);
RcppExport SEXP _ldmppr_dist_one_dim(SEXP eval_tSEXP, SEXP obs_tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type eval_t(eval_tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type obs_t(obs_tSEXP);
    rcpp_result_gen = Rcpp::wrap(dist_one_dim(eval_t, obs_t));
    return rcpp_result_gen;
END_RCPP
}
// part_1_1_full
double part_1_1_full(NumericMatrix data, NumericVector params);
RcppExport SEXP _ldmppr_part_1_1_full(SEXP dataSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(part_1_1_full(data, params));
    return rcpp_result_gen;
END_RCPP
}
// part_1_2_full
double part_1_2_full(NumericMatrix data, NumericVector params);
RcppExport SEXP _ldmppr_part_1_2_full(SEXP dataSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(part_1_2_full(data, params));
    return rcpp_result_gen;
END_RCPP
}
// part_1_3_full
double part_1_3_full(NumericVector xgrid, NumericVector ygrid, NumericVector tgrid, NumericMatrix data, NumericVector params, NumericVector bounds);
RcppExport SEXP _ldmppr_part_1_3_full(SEXP xgridSEXP, SEXP ygridSEXP, SEXP tgridSEXP, SEXP dataSEXP, SEXP paramsSEXP, SEXP boundsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type xgrid(xgridSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ygrid(ygridSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tgrid(tgridSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bounds(boundsSEXP);
    rcpp_result_gen = Rcpp::wrap(part_1_3_full(xgrid, ygrid, tgrid, data, params, bounds));
    return rcpp_result_gen;
END_RCPP
}
// part_1_4_full
double part_1_4_full(NumericMatrix data, NumericVector params);
RcppExport SEXP _ldmppr_part_1_4_full(SEXP dataSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(part_1_4_full(data, params));
    return rcpp_result_gen;
END_RCPP
}
// part_1_full
double part_1_full(NumericVector xgrid, NumericVector ygrid, NumericVector tgrid, NumericMatrix data, NumericVector params, NumericVector bounds);
RcppExport SEXP _ldmppr_part_1_full(SEXP xgridSEXP, SEXP ygridSEXP, SEXP tgridSEXP, SEXP dataSEXP, SEXP paramsSEXP, SEXP boundsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type xgrid(xgridSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ygrid(ygridSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tgrid(tgridSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bounds(boundsSEXP);
    rcpp_result_gen = Rcpp::wrap(part_1_full(xgrid, ygrid, tgrid, data, params, bounds));
    return rcpp_result_gen;
END_RCPP
}
// part_2_full
double part_2_full(NumericVector xgrid, NumericVector ygrid, NumericVector tgrid, NumericMatrix data, NumericVector params, NumericVector bounds);
RcppExport SEXP _ldmppr_part_2_full(SEXP xgridSEXP, SEXP ygridSEXP, SEXP tgridSEXP, SEXP dataSEXP, SEXP paramsSEXP, SEXP boundsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type xgrid(xgridSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ygrid(ygridSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tgrid(tgridSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bounds(boundsSEXP);
    rcpp_result_gen = Rcpp::wrap(part_2_full(xgrid, ygrid, tgrid, data, params, bounds));
    return rcpp_result_gen;
END_RCPP
}
// full_sc_lhood
double full_sc_lhood(NumericVector xgrid, NumericVector ygrid, NumericVector tgrid, NumericVector tobs, NumericMatrix data, NumericVector params, NumericVector bounds);
RcppExport SEXP _ldmppr_full_sc_lhood(SEXP xgridSEXP, SEXP ygridSEXP, SEXP tgridSEXP, SEXP tobsSEXP, SEXP dataSEXP, SEXP paramsSEXP, SEXP boundsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type xgrid(xgridSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ygrid(ygridSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tgrid(tgridSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tobs(tobsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bounds(boundsSEXP);
    rcpp_result_gen = Rcpp::wrap(full_sc_lhood(xgrid, ygrid, tgrid, tobs, data, params, bounds));
    return rcpp_result_gen;
END_RCPP
}
// spat_interaction
double spat_interaction(NumericMatrix Hist, NumericVector newp, NumericVector params);
RcppExport SEXP _ldmppr_spat_interaction(SEXP HistSEXP, SEXP newpSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Hist(HistSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type newp(newpSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(spat_interaction(Hist, newp, params));
    return rcpp_result_gen;
END_RCPP
}
// interaction_st
NumericVector interaction_st(NumericMatrix data, NumericVector params);
RcppExport SEXP _ldmppr_interaction_st(SEXP dataSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(interaction_st(data, params));
    return rcpp_result_gen;
END_RCPP
}
// temporal_sc
double temporal_sc(NumericVector params, double eval_t, NumericVector obs_t);
RcppExport SEXP _ldmppr_temporal_sc(SEXP paramsSEXP, SEXP eval_tSEXP, SEXP obs_tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< double >::type eval_t(eval_tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type obs_t(obs_tSEXP);
    rcpp_result_gen = Rcpp::wrap(temporal_sc(params, eval_t, obs_t));
    return rcpp_result_gen;
END_RCPP
}
// sim_temporal_sc
NumericVector sim_temporal_sc(double Tmin, double Tmax, NumericVector params);
RcppExport SEXP _ldmppr_sim_temporal_sc(SEXP TminSEXP, SEXP TmaxSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type Tmin(TminSEXP);
    Rcpp::traits::input_parameter< double >::type Tmax(TmaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_temporal_sc(Tmin, Tmax, params));
    return rcpp_result_gen;
END_RCPP
}
// sim_spatial_sc
NumericMatrix sim_spatial_sc(NumericVector M_n, NumericVector params, int nsim_t, NumericVector xy_bounds);
RcppExport SEXP _ldmppr_sim_spatial_sc(SEXP M_nSEXP, SEXP paramsSEXP, SEXP nsim_tSEXP, SEXP xy_boundsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type M_n(M_nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< int >::type nsim_t(nsim_tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xy_bounds(xy_boundsSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_spatial_sc(M_n, params, nsim_t, xy_bounds));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ldmppr_vec_dist", (DL_FUNC) &_ldmppr_vec_dist, 2},
    {"_ldmppr_full_product", (DL_FUNC) &_ldmppr_full_product, 5},
    {"_ldmppr_C_theta2_i", (DL_FUNC) &_ldmppr_C_theta2_i, 6},
    {"_ldmppr_conditional_sum", (DL_FUNC) &_ldmppr_conditional_sum, 3},
    {"_ldmppr_conditional_sum_logical", (DL_FUNC) &_ldmppr_conditional_sum_logical, 3},
    {"_ldmppr_vec_to_mat_dist", (DL_FUNC) &_ldmppr_vec_to_mat_dist, 2},
    {"_ldmppr_dist_one_dim", (DL_FUNC) &_ldmppr_dist_one_dim, 2},
    {"_ldmppr_part_1_1_full", (DL_FUNC) &_ldmppr_part_1_1_full, 2},
    {"_ldmppr_part_1_2_full", (DL_FUNC) &_ldmppr_part_1_2_full, 2},
    {"_ldmppr_part_1_3_full", (DL_FUNC) &_ldmppr_part_1_3_full, 6},
    {"_ldmppr_part_1_4_full", (DL_FUNC) &_ldmppr_part_1_4_full, 2},
    {"_ldmppr_part_1_full", (DL_FUNC) &_ldmppr_part_1_full, 6},
    {"_ldmppr_part_2_full", (DL_FUNC) &_ldmppr_part_2_full, 6},
    {"_ldmppr_full_sc_lhood", (DL_FUNC) &_ldmppr_full_sc_lhood, 7},
    {"_ldmppr_spat_interaction", (DL_FUNC) &_ldmppr_spat_interaction, 3},
    {"_ldmppr_interaction_st", (DL_FUNC) &_ldmppr_interaction_st, 2},
    {"_ldmppr_temporal_sc", (DL_FUNC) &_ldmppr_temporal_sc, 3},
    {"_ldmppr_sim_temporal_sc", (DL_FUNC) &_ldmppr_sim_temporal_sc, 3},
    {"_ldmppr_sim_spatial_sc", (DL_FUNC) &_ldmppr_sim_spatial_sc, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_ldmppr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
