#' estimate parameters of self-correcting model using log-likelihood maximization
#'
#' @param xgrid a vector of grid values for x
#' @param ygrid a vector of gridyvalues for y
#' @param tgrid a vector of grid values for t
#' @param data a matrix of times and locations
#' @param parameter_inits a vector of parameter initialization values
#' @param bounds a vector of bounds for time, x, and y
#' @param opt_algorithm the NLopt algorithm to use for maximization
#' @param nloptr_options a list of named options including "maxeval", "xtol_rel", and "maxtime"
#' @param verbose `TRUE` or `FALSE` indicating whether to show progress of optimization
#'
#' @return an nloptr object with details of the optimization including solution
#' @export
#'
estimate_parameters_sc <- function(xgrid, ygrid, tgrid, data, parameter_inits,
                                   bounds, opt_algorithm = "NLOPT_GN_DIRECT_L",
                                   nloptr_options = list(maxeval = 400,
                                                         xtol_rel = 1e-5,
                                                         maxtime = NULL),
                                   verbose = TRUE)  {

  # Define a function to evaluate the self-correcting model full likelihood given a set of parameter values
  opt_likeli <- function(parameters) {
    likeli <- full_sc_lhood(xgrid = xgrid, ygrid = ygrid, tgrid = tgrid, tobs = data[,1],
                            data = data, params = parameters, bounds = bounds)
    return(-likeli)
  }

  if(verbose){
    # Prints values per iteration
    print_opts <- 2
  } else{
    # Prints nothing
    print_opts <- 0
  }

  # Track the time to run
  ptm <- base::proc.time()

  # Perform the optimization of the likelihood
  parameter_estimates <- nloptr::nloptr(x0 = parameter_inits,
                                        eval_f = opt_likeli,
                                        lb = c(-Inf, 0, 0, 0, 0, 0, 0, 0),
                                        ub = c(Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf),
                                        opts = list("algorithm" = opt_algorithm,
                                                    "maxeval" = nloptr_options[["maxeval"]],
                                                    "xtol_rel" = nloptr_options[["xtol_rel"]],
                                                    "maxtime" = nloptr_options[["maxtime"]],
                                                    "print_level" = print_opts))
  # Print the time to run if verbose = TRUE
  if(verbose){
    base::message("Total time to run:")
    print(base::proc.time() - ptm)
  }

  # Return the nloptr object generated by the optimization
  return(parameter_estimates)
}


