# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' calculates euclidean distance
#'
#' @param x a vector x
#' @param y a vector y
#'
#' @returns distance between the two vectors
#' @export
pdistCVec <- function(x, y) {
    .Call('_ldmppr_pdistCVec', PACKAGE = 'ldmppr', x, y)
}

#' calculates full product
#'
#' @param xgrid a vector of grid values for x
#' @param ygrid a vector of grid values for y
#' @param tgrid a t value
#' @param data a matrix of data
#' @param params a vector of parameters
#'
#' @returns returns the product
#' @export
prodFullCpp <- function(xgrid, ygrid, tgrid, data, params) {
    .Call('_ldmppr_prodFullCpp', PACKAGE = 'ldmppr', xgrid, ygrid, tgrid, data, params)
}

#' calculates c_theta
#'
#' @param xgrid a vector of grid values for x
#' @param ygrid a vector of grid values for y
#' @param tgrid a t value
#' @param data a matrix of data
#' @param params a vector of parameters
#' @param bounds a vector of bounds for time, x, and y
#'
#' @returns returns the product
#' @export
Ctheta2i <- function(xgrid, ygrid, tgrid, data, params, bounds) {
    .Call('_ldmppr_Ctheta2i', PACKAGE = 'ldmppr', xgrid, ygrid, tgrid, data, params, bounds)
}

#' calculates sum of values < t
#'
#' @param obst a vector of observed t
#' @param evalt a t value
#' @param y a vector of values
#'
#' @returns the sum
#' @export
CondSumCpp <- function(obst, evalt, y) {
    .Call('_ldmppr_CondSumCpp', PACKAGE = 'ldmppr', obst, evalt, y)
}

#' calculates sum of values < t
#'
#' @param obst a vector of observed t
#' @param evalt a t value
#' @param y a vector of values
#'
#' @returns the sum
#' @export
CondSumCppR <- function(obst, evalt, y) {
    .Call('_ldmppr_CondSumCppR', PACKAGE = 'ldmppr', obst, evalt, y)
}

#' calculates euclidean distance
#'
#' @param evalu a vector
#' @param obsu a matrix
#'
#' @returns distance between a vector and each row of a matrix
#' @export
pdistC <- function(evalu, obsu) {
    .Call('_ldmppr_pdistC', PACKAGE = 'ldmppr', evalu, obsu)
}

#' calculates distance in one dim
#'
#' @param evalt a t value
#' @param obst a vector of t
#'
#' @returns distance between a t and all t
#' @export
rdistC <- function(evalt, obst) {
    .Call('_ldmppr_rdistC', PACKAGE = 'ldmppr', evalt, obst)
}

#' calculates part 2
#'
#' @param xgrid a vector of grid values for x
#' @param ygrid a vector of grid values for y
#' @param tgrid a t value
#' @param data a matrix of data
#' @param param a vector of parameters
#' @param bounds a vector of bounds for time, x, and y
#'
#' @returns distance between a t and all t
#' @export
Part2FullCpp <- function(xgrid, ygrid, tgrid, data, param, bounds) {
    .Call('_ldmppr_Part2FullCpp', PACKAGE = 'ldmppr', xgrid, ygrid, tgrid, data, param, bounds)
}

#' calculates part 1-1 full
#'
#' @param data a matrix of locations and times
#' @param paramt a vector of parameters
#' @returns full likelihood for part 1
#' @export
Part1_1FullCpp <- function(data, paramt) {
    .Call('_ldmppr_Part1_1FullCpp', PACKAGE = 'ldmppr', data, paramt)
}

#' calculates part 1-2 full
#'
#' @param data a matrix of locations and times
#' @param params a vector of parameters
#' @returns full likelihood for part 2
#' @export
Part1_2FullCpp <- function(data, params) {
    .Call('_ldmppr_Part1_2FullCpp', PACKAGE = 'ldmppr', data, params)
}

#' calculates part 1-3
#'
#' @param xgrid a vector of grid values for x
#' @param ygrid a vector of grid values for y
#' @param tgrid a t value
#' @param data a matrix of data
#' @param params a vector of parameters
#' @param bounds a vector of time, x, and y bounds
#'
#' @returns full likelihood for part 3
#' @export
Part1_3FullCpp <- function(xgrid, ygrid, tgrid, data, params, bounds) {
    .Call('_ldmppr_Part1_3FullCpp', PACKAGE = 'ldmppr', xgrid, ygrid, tgrid, data, params, bounds)
}

#' calculates part 1-4
#'
#' @param data a matrix of locations and times
#' @param paramg a vector of parameters
#'
#' @returns full likelihood for part 4
#' @export
Part1_4FullCpp <- function(data, paramg) {
    .Call('_ldmppr_Part1_4FullCpp', PACKAGE = 'ldmppr', data, paramg)
}

#' calculates spatial interaction
#'
#' @param Hist a matrix of points
#' @param newp a new point vector
#' @param par a vector of parameters
#'
#' @returns probability of new point
#' @export
interactionCpp <- function(Hist, newp, par) {
    .Call('_ldmppr_interactionCpp', PACKAGE = 'ldmppr', Hist, newp, par)
}

#' calculates spatio-temporal interaction
#'
#' @param data a matrix of points and times
#' @param paramg a vector of parameters
#'
#' @returns interaction probabilities for every point
#' @export
interactionCpp_st <- function(data, paramg) {
    .Call('_ldmppr_interactionCpp_st', PACKAGE = 'ldmppr', data, paramg)
}

