# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' calculates euclidean distance
#'
#' @param x a vector x
#' @param y a vector y
#'
#' @returns distance between the two vectors
#' @keywords internal
pdistCVec <- function(x, y) {
    .Call('_ldmppr_pdistCVec', PACKAGE = 'ldmppr', x, y)
}

#' calculates full product
#'
#' @param xgrid a vector of grid values for x
#' @param ygrid a vector of grid values for y
#' @param tgrid a t value
#' @param data a matrix of data
#' @param params a vector of parameters
#'
#' @returns returns the product
#' @keywords internal
prodFullCpp <- function(xgrid, ygrid, tgrid, data, params) {
    .Call('_ldmppr_prodFullCpp', PACKAGE = 'ldmppr', xgrid, ygrid, tgrid, data, params)
}

#' calculates c_theta
#'
#' @param xgrid a vector of grid values for x
#' @param ygrid a vector of grid values for y
#' @param tgrid a t value
#' @param data a matrix of data
#' @param params a vector of parameters
#' @param bounds a vector of bounds for time, x, and y
#'
#' @returns returns the product
#' @keywords internal
Ctheta2i <- function(xgrid, ygrid, tgrid, data, params, bounds) {
    .Call('_ldmppr_Ctheta2i', PACKAGE = 'ldmppr', xgrid, ygrid, tgrid, data, params, bounds)
}

#' calculates sum of values < t
#'
#' @param obst a vector of observed t
#' @param evalt a t value
#' @param y a vector of values
#'
#' @returns the sum
#' @keywords internal
CondSumCpp <- function(obst, evalt, y) {
    .Call('_ldmppr_CondSumCpp', PACKAGE = 'ldmppr', obst, evalt, y)
}

#' calculates sum of values < t
#'
#' @param obst a vector of observed t
#' @param evalt a t value
#' @param y a vector of values
#'
#' @returns the sum
#' @keywords internal
CondSumCppR <- function(obst, evalt, y) {
    .Call('_ldmppr_CondSumCppR', PACKAGE = 'ldmppr', obst, evalt, y)
}

#' calculates euclidean distance
#'
#' @param evalu a vector
#' @param obsu a matrix
#'
#' @returns distance between a vector and each row of a matrix
#' @keywords internal
pdistC <- function(evalu, obsu) {
    .Call('_ldmppr_pdistC', PACKAGE = 'ldmppr', evalu, obsu)
}

#' calculates distance in one dim
#'
#' @param evalt a t value
#' @param obst a vector of t
#'
#' @returns distance between a t and all t
#' @keywords internal
rdistC <- function(evalt, obst) {
    .Call('_ldmppr_rdistC', PACKAGE = 'ldmppr', evalt, obst)
}

#' calculates part 2
#'
#' @param xgrid a vector of grid values for x
#' @param ygrid a vector of grid values for y
#' @param tgrid a vector of grid values for t
#' @param data a matrix of times and locations
#' @param params a vector of parameters
#' @param bounds a vector of bounds for time, x, and y
#'
#' @returns second part of likelihood
#' @keywords internal
Part2FullCpp <- function(xgrid, ygrid, tgrid, data, params, bounds) {
    .Call('_ldmppr_Part2FullCpp', PACKAGE = 'ldmppr', xgrid, ygrid, tgrid, data, params, bounds)
}

#' calculates part 1-1 full
#'
#' @param data a matrix of locations and times
#' @param paramt a vector of parameters
#'
#' @returns full likelihood for part 1
#' @keywords internal
Part1_1FullCpp <- function(data, paramt) {
    .Call('_ldmppr_Part1_1FullCpp', PACKAGE = 'ldmppr', data, paramt)
}

#' calculates part 1-2 full
#'
#' @param data a matrix of locations and times
#' @param params a vector of parameters
#'
#' @returns full likelihood for part 2
#' @keywords internal
Part1_2FullCpp <- function(data, params) {
    .Call('_ldmppr_Part1_2FullCpp', PACKAGE = 'ldmppr', data, params)
}

#' calculates part 1-3
#'
#' @param xgrid a vector of grid values for x
#' @param ygrid a vector of grid values for y
#' @param tgrid a t value
#' @param data a matrix of times and locations
#' @param params a vector of parameters
#' @param bounds a vector of time, x, and y bounds
#'
#' @returns full likelihood for part 3
#' @keywords internal
Part1_3FullCpp <- function(xgrid, ygrid, tgrid, data, params, bounds) {
    .Call('_ldmppr_Part1_3FullCpp', PACKAGE = 'ldmppr', xgrid, ygrid, tgrid, data, params, bounds)
}

#' calculates part 1-4
#'
#' @param data a matrix of times and locations
#' @param paramg a vector of parameters
#'
#' @returns full likelihood for part 4
#' @keywords internal
Part1_4FullCpp <- function(data, paramg) {
    .Call('_ldmppr_Part1_4FullCpp', PACKAGE = 'ldmppr', data, paramg)
}

#' calculates part 1
#'
#' @param xgrid a vector of grid values for x
#' @param ygrid a vector of grid values for y
#' @param tgrid a t value
#' @param data a matrix of times and locations
#' @param params a vector of parameters
#' @param bounds a vector of bounds for time, x, and y
#'
#' @returns first part of likelihood
#' @keywords internal
Part1FullCpp <- function(xgrid, ygrid, tgrid, data, params, bounds) {
    .Call('_ldmppr_Part1FullCpp', PACKAGE = 'ldmppr', xgrid, ygrid, tgrid, data, params, bounds)
}

#' calculates full self-correcting log-likelihood
#'
#' @param xgrid a vector of grid values for x
#' @param ygrid a vector of grid values for y
#' @param tgrid a vector of grid values for t
#' @param tobs a vector of observed values for t
#' @param data a matrix of times and locations
#' @param params a vector of parameters
#' @param bounds a vector of bounds for time, x, and y
#'
#' @returns full log-likelihood
#' @keywords internal
full_sc_lhood <- function(xgrid, ygrid, tgrid, tobs, data, params, bounds) {
    .Call('_ldmppr_full_sc_lhood', PACKAGE = 'ldmppr', xgrid, ygrid, tgrid, tobs, data, params, bounds)
}

#' calculates spatial interaction
#'
#' @param Hist a matrix of points
#' @param newp a new point vector
#' @param par a vector of parameters
#'
#' @returns probability of new point
#' @keywords internal
interactionCpp <- function(Hist, newp, par) {
    .Call('_ldmppr_interactionCpp', PACKAGE = 'ldmppr', Hist, newp, par)
}

#' calculates spatio-temporal interaction
#'
#' @param data a matrix of times and locations
#' @param paramg a vector of parameters
#'
#' @returns interaction probabilities for every point
#' @keywords internal
interactionCpp_st <- function(data, paramg) {
    .Call('_ldmppr_interactionCpp_st', PACKAGE = 'ldmppr', data, paramg)
}

#' calculates temporal likelihood
#'
#' @param par a vector of parameters (alpha_1, beta_1, gamma_1)
#' @param evalt a t value
#' @param obst a vector of t
#'
#' @returns full temporal likelihood evaluation
#' @keywords internal
temporal_sc_cpp <- function(par, evalt, obst) {
    .Call('_ldmppr_temporal_sc_cpp', PACKAGE = 'ldmppr', par, evalt, obst)
}

#' Simulate the temporal component of the self-correcting model
#'
#' @param Tmin minimum time value
#' @param Tmax maximum time value
#' @param params a vector of parameters (alpha_1, beta_1, gamma_1)
#'
#' @return a vector of thinned and temporal samples
#' @keywords internal
sim_temporal_sc_cpp <- function(Tmin = 0, Tmax = 1, params = as.numeric( c(0, 0, 0))) {
    .Call('_ldmppr_sim_temporal_sc_cpp', PACKAGE = 'ldmppr', Tmin, Tmax, params)
}

#' Simulate the spatial component of the self-correcting model
#'
#' @param M_n vector of (x,y)-coordinates for largest point
#' @param params a vector of parameters (alpha_2, beta_2)
#' @param nsim_t number of points to simulate
#' @param xy_bounds vector of lower and upper bounds for the domain (2 for x, 2 for y)
#'
#' @return a matrix of point locations in the (x,y)-plane
#' @keywords internal
sim_spatial_sc_cpp <- function(M_n, params, nsim_t, xy_bounds) {
    .Call('_ldmppr_sim_spatial_sc_cpp', PACKAGE = 'ldmppr', M_n, params, nsim_t, xy_bounds)
}

